"""change embedding dimension to 384

Revision ID: a8814e762a4f
Revises: 4261aa4a3152
Create Date: 2026-08-17 15:08:01.646995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'a8814e762a4f'
down_revision: Union[str, Sequence[str], None] = '4261aa4a3152'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("TRUNCATE TABLE document_chunks")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_chunks', 'embedding', type_=Vector(384), postgresql_using='embedding::vector(384)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               existing_nullable=False)
    # ### end Alembic commands ###
